# Catppuccin themes for Spotify-player

[[themes]]
name = "Catppuccin-mocha"
[themes.palette]

foreground = "#CDD6F4"
black = "#89B4FA"
blue = "#89B4FA"
cyan = "#89B4FA"
green = "#89B4FA"
magenta = "#89B4FA"
red = "#F38BA8"
white = "#CDD6F4"
yellow = "#F9E2AF"
bright_black = "#45475a"
bright_blue = "#89B4FA"
bright_cyan = "#89B4FA"
bright_green = "#A6E3A1"
bright_magenta = "#CBA6F7"
bright_red = "#F38BA8"
bright_white = "#CDD6F4"
bright_yellow = "#F9E2AF"

[themes.component_style]
selection = { bg = "#313244", modifiers = ["Bold"] }
